# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Lecture11-FireBaseDemo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lecture11-FireBaseDemo
  pod 'Firebase'
  pod 'Firebase/Database'

  target 'Lecture11-FireBaseDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Lecture11-FireBaseDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
