# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Lecture08-PuppyFlix' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lecture08-PuppyFlix
  pod 'TUSafariActivity', '~> 1.0'


  target 'Lecture08-PuppyFlixTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Lecture08-PuppyFlixUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
